### Parametrizando en el query directamente
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  getAllBooks {
    asin
    title
  }
}

### Parametrizando a través de variables
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  getBook(asin: "B00ICN066A") {
    asin
    title
  }
}


### Update the title of the B00DQ845EA book
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation {
  updateBook(asin: "B00DQ845EA", title: "The Hard Thing About Hard Things: Building a Business When There Are No Easy Answers") {
    asin
    title
  }
}

