### Obtener todos los lives
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  getAllLives {
    id
    title
    subtitle
    date
    time
    mode
    img
  }
}

### Obtener un live por "id"
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  getLive(id: "966e943b-b112-4eed-92eb-24c1ff9b2972") {
    id
    title
    subtitle
    date
    time
    mode
    img
  }
}
