#############################
### Insert live SIN token ###
#############################
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation {
  insertLive(
    id: "69d80629-e055-4a30-b5be-0dce199071e9"
    title: "Salud Mental",
    subtitle: "El componente necesario en tu organización",
    date: "2022-03-15",
    time: "19:00:000",
    mode: "online",
    img: "https://bedu.org/_next/image?url=https%3A%2F%2Fimg.evbuc.com%2Fhttps%253A%252F%252Fcdn.evbuc.com%252Fimages%252F245075949%252F185160745410%252F1%252Foriginal.20220310-180313%3Fh%3D200%26w%3D450%26auto%3Dformat%252Ccompress%26q%3D75%26sharp%3D10%26rect%3D0%252C0%252C2160%252C1080%26s%3D1a1324c3061e0517dba0b93e204ee5e5&w=2048&q=75"
  ) {
    id
    title
  }
}

### Insert a live
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation {
  insertLive(
    id: "cb6e87b1-8096-4c7c-9281-39f4d2328119"
    title: "Empresas más ágiles con Product Discovery",
    date: "2022-03-17",
    time: "19:00:000",
    mode: "online",
    img: "https://bedu.org/_next/image?url=https%3A%2F%2Fimg.evbuc.com%2Fhttps%253A%252F%252Fcdn.evbuc.com%252Fimages%252F232938469%252F185160745410%252F1%252Foriginal.20220219-014720%3Fh%3D200%26w%3D450%26auto%3Dformat%252Ccompress%26q%3D75%26sharp%3D10%26rect%3D0%252C0%252C2160%252C1080%26s%3D1f48b306478b097a888f26ee02142239&w=2048&q=75"
  ) {
    id
    title
  }
}

### Insert a live
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation {
  insertLive(
    id: "6f27f4be-2053-4c01-a203-43f9a876b0e4"
    title: "DevOps",
    subtitle: "El puente Tech que necesita tu empresa",
    date: "2022-03-22",
    time: "19:00:000",
    mode: "online",
    img: "https://bedu.org/_next/image?url=https%3A%2F%2Fimg.evbuc.com%2Fhttps%253A%252F%252Fcdn.evbuc.com%252Fimages%252F232944139%252F185160745410%252F1%252Foriginal.20220219-015817%3Fh%3D200%26w%3D450%26auto%3Dformat%252Ccompress%26q%3D75%26sharp%3D10%26rect%3D0%252C0%252C2160%252C1080%26s%3Dd7d1b4644c12479aed0640957f798899&w=2048&q=75"
  ) {
    id
    title
  }
}

### Insert a live
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation {
  insertLive(
    id: "0fbe36b4-4a25-4d39-9544-c23504442dfb"
    title: "Data Driven",
    subtitle: "en Programmatic Advertising",
    date: "2022-03-24",
    time: "19:00:000",
    mode: "online",
    img: "https://bedu.org/_next/image?url=https%3A%2F%2Fimg.evbuc.com%2Fhttps%253A%252F%252Fcdn.evbuc.com%252Fimages%252F232945379%252F185160745410%252F1%252Foriginal.20220219-021708%3Fh%3D200%26w%3D450%26auto%3Dformat%252Ccompress%26q%3D75%26sharp%3D10%26rect%3D0%252C0%252C2160%252C1080%26s%3Da7713072ec29c99de45172cedd005974&w=2048&q=75"
  ) {
    id
    title
  }
}



#############################
### Insert live CON token ###
#############################
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkJldG8gQmVkdSIsImVtYWlsIjoiYmV0b0BiZWR1Lm9yZyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NzQ3Nzk2MiwiZXhwIjoxNjQ3NDc4MTQyfQ.LD4FuCYBpNeIJv9paOHkp7M1oG2IzKYYju0SKstmw7o

mutation {
  insertLive(
    id: "69d80629-e055-4a30-b5be-0dce199071e9"
    title: "Salud Mental",
    subtitle: "El componente necesario en tu organización",
    date: "2022-03-15",
    time: "19:00:000",
    mode: "online",
    img: "https://bedu.org/_next/image?url=https%3A%2F%2Fimg.evbuc.com%2Fhttps%253A%252F%252Fcdn.evbuc.com%252Fimages%252F245075949%252F185160745410%252F1%252Foriginal.20220310-180313%3Fh%3D200%26w%3D450%26auto%3Dformat%252Ccompress%26q%3D75%26sharp%3D10%26rect%3D0%252C0%252C2160%252C1080%26s%3D1a1324c3061e0517dba0b93e204ee5e5&w=2048&q=75"
  ) {
    id
    title
  }
}

### Insert a live
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkJldG8gQmVkdSIsImVtYWlsIjoiYmV0b0BiZWR1Lm9yZyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NzQ3Nzk2MiwiZXhwIjoxNjQ3NDc4MTQyfQ.LD4FuCYBpNeIJv9paOHkp7M1oG2IzKYYju0SKstmw7o

mutation {
  insertLive(
    id: "cb6e87b1-8096-4c7c-9281-39f4d2328119"
    title: "Empresas más ágiles con Product Discovery",
    date: "2022-03-17",
    time: "19:00:000",
    mode: "online",
    img: "https://bedu.org/_next/image?url=https%3A%2F%2Fimg.evbuc.com%2Fhttps%253A%252F%252Fcdn.evbuc.com%252Fimages%252F232938469%252F185160745410%252F1%252Foriginal.20220219-014720%3Fh%3D200%26w%3D450%26auto%3Dformat%252Ccompress%26q%3D75%26sharp%3D10%26rect%3D0%252C0%252C2160%252C1080%26s%3D1f48b306478b097a888f26ee02142239&w=2048&q=75"
  ) {
    id
    title
  }
}

### Insert a live
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkJldG8gQmVkdSIsImVtYWlsIjoiYmV0b0BiZWR1Lm9yZyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NzQ3Nzk2MiwiZXhwIjoxNjQ3NDc4MTQyfQ.LD4FuCYBpNeIJv9paOHkp7M1oG2IzKYYju0SKstmw7o

mutation {
  insertLive(
    id: "6f27f4be-2053-4c01-a203-43f9a876b0e4"
    title: "DevOps",
    subtitle: "El puente Tech que necesita tu empresa",
    date: "2022-03-22",
    time: "19:00:000",
    mode: "online",
    img: "https://bedu.org/_next/image?url=https%3A%2F%2Fimg.evbuc.com%2Fhttps%253A%252F%252Fcdn.evbuc.com%252Fimages%252F232944139%252F185160745410%252F1%252Foriginal.20220219-015817%3Fh%3D200%26w%3D450%26auto%3Dformat%252Ccompress%26q%3D75%26sharp%3D10%26rect%3D0%252C0%252C2160%252C1080%26s%3Dd7d1b4644c12479aed0640957f798899&w=2048&q=75"
  ) {
    id
    title
  }
}

### Insert a live
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkJldG8gQmVkdSIsImVtYWlsIjoiYmV0b0BiZWR1Lm9yZyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NzQ3Nzk2MiwiZXhwIjoxNjQ3NDc4MTQyfQ.LD4FuCYBpNeIJv9paOHkp7M1oG2IzKYYju0SKstmw7o

mutation {
  insertLive(
    id: "0fbe36b4-4a25-4d39-9544-c23504442dfb"
    title: "Data Driven",
    subtitle: "en Programmatic Advertising",
    date: "2022-03-24",
    time: "19:00:000",
    mode: "online",
    img: "https://bedu.org/_next/image?url=https%3A%2F%2Fimg.evbuc.com%2Fhttps%253A%252F%252Fcdn.evbuc.com%252Fimages%252F232945379%252F185160745410%252F1%252Foriginal.20220219-021708%3Fh%3D200%26w%3D450%26auto%3Dformat%252Ccompress%26q%3D75%26sharp%3D10%26rect%3D0%252C0%252C2160%252C1080%26s%3Da7713072ec29c99de45172cedd005974&w=2048&q=75"
  ) {
    id
    title
  }
}
