### Obtener todos los lives
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  getAllLives {
    id
    title
  }
}

### Obtener un solo live
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  getLive(id: "6f27f4be-2053-4c01-a203-43f9a876b0e4") {
    title
    subtitle
  }
}

############################
### Obtener todos los lives
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkJldG8gQmVkdSIsImVtYWlsIjoiYmV0b0BiZWR1Lm9yZyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NzQ3Njg1NCwiZXhwIjoxNjQ3NDc3MDM0fQ.BzqWpuyw_Tru3uhpgI9kY8CTA6HRKS9o1BFPDOA6MTo

query {
  getAllLives {
    id
    title
  }
}

### Obtener un solo live
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkJldG8gQmVkdSIsImVtYWlsIjoiYmV0b0BiZWR1Lm9yZyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NzQ3Njg1NCwiZXhwIjoxNjQ3NDc3MDM0fQ.BzqWpuyw_Tru3uhpgI9kY8CTA6HRKS9o1BFPDOA6MTo

query {
  getLive(id: "6f27f4be-2053-4c01-a203-43f9a876b0e4") {
    title
    subtitle
  }
}


