### Parametrizando en el query directamente
POST http://127.0.0.1:4000 HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  hello(nombre: "Beto")
}

### Parametrizando a través de variables
POST http://127.0.0.1:4000 HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query ($nombre: String!) {
  hello(nombre: $nombre)
}

{
  "nombre": "Gaby"
}