### Obtener todos los libros
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  getAllBooks {
    asin
    title
  }
}

### Obtener un solo libro
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  getBook(asin: "B00ICN066A") {
    asin
    title
  }
}
