#################################
### Update de title sin token ###
#################################
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation {
  updateBook(asin: "B00DQ845EA", title: "The Hard Thing About Hard Things: Building a Business When There Are No Easy Answers") {
    asin
    title
  }
}
#################################
### Update de title con token ###
#################################
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6IkJldG8gQmVkdSIsImVtYWlsIjoiYmV0b0BiZWR1Lm9yZyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NzQ1NzE3MSwiZXhwIjoxNjQ3NDU3MzUxfQ.O2q6WnvVnbFRP8AhpK6rsGcvb12SPPsWhTVFU7dIxPI

mutation {
  updateBook(asin: "B00DQ845EA", title: "The Hard Thing About Hard Things: Building a Business When There Are No Easy Answers") {
    asin
    title
  }
}