### Update the title of the 3rd live
POST http://127.0.0.1:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation {
  updateLive(id: "6f27f4be-2053-4c01-a203-43f9a876b0e4", title: "DevSecOps") {
    id
    title
  }
}
